### ISSUE TITLE
Delete an entry from within _array

### ISSUE THREAD

**Issue by mg03** [chrisroberts/attribute_struct#3]
Hi
@struct = AttributeStruct.new do
my_array _array(
-> {
working true
},
:item
)
end
Is it possible to delete working from my_array and add a different element
@struct._delete(:my_array[0][:working]
Thanx

**Comment by chrisroberts** [comment]
Hi. Yes, it works like a normal Array. For example:

```ruby
AttributeStruct.new do
  my_array _array(->{ working true}, :item)
  my_array.delete_at(0)
end.dump
```
which will result with:

```
=> {"my_array" => [:item]}
```

If you want to delete the item based on the content rather than the index location, you can do that as well (note we have to check type since you have mixed types in the array):

```ruby
AttributeStruct.new do
  my_array _array(->{ working true}, :item)
  my_array.delete_if do |element|
    element.is_a?(AttributeStruct) && element[:working] == true
  end
end.dump
```

which will give the same result:

```
=> {"my_array" => [:item]}
```

but in this version the element can be anywhere in the array. Hope that helps! Let me know if that solves your problem.

Cheers!

**Comment by mg03** [comment]
Hi 

Thanx for the quick response. This helps .

Regards
